### ISSUE TITLE
Missing libcxx Runtime

### ISSUE THREAD

**Issue by siefkenj** [flathub/org.freedesktop.Sdk.Extension.llvm17#6]
I don't know if this is supposed to be in a different extension or not, but it appears that this extension does not build `libc++.so.1`, which would be enabled via `-DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi"` and `ninja -C build install-cxx install-cxxabi`

Would you be able to enable these libraries?

**Comment by Erick555** [comment]
Yes, libc++ isn't part of the extension and I'm not sure it should be - if your app links to it then you must copy the lib from extension to app after the build which may be [doable](https://github.com/flathub/org.freedesktop.Sdk.Extension.llvm17?tab=readme-ov-file#troubleshooting) but isn't very convenient. Extension is mostly aimed for being a build toolchain/debug tool than runtime dependency and runtime deps apps can bundle themselves.

Can you tell what's your use case for libc++? Is your app linking to it?

**Comment by siefkenj** [comment]
I am trying to package Gyroflow and am running into trouble https://github.com/gyroflow/gyroflow/issues/57

I've tried to bundle `libc++` myself, but I get an error that I don't have permissions to copy into `/usr/lib`

```yml
id: xyz.gyroflow.Gyroflow
runtime: org.kde.Platform
runtime-version: '6.7'
sdk: org.kde.Sdk
sdk-extensions:
  - "org.freedesktop.Sdk.Extension.rust-stable"
  - "org.freedesktop.Sdk.Extension.llvm17"
command: gyroflow

build-options:
  env: 
    CARGO_HOME: /run/build/gyroflow/cargo
    
  append-path: /usr/lib/sdk/rust-stable/bin
  append-path: /run/build/gyroflow/cargo/bin
  prepend-path: /usr/lib/sdk/llvm17/bin
  prepend-ld-library-path: /usr/lib/sdk/llvm17/lib
  build-args:
    - --share=network
    
modules:
  - name: libcxx
    buildsystem: simple
    builddir: true
    sources: 
      - type: archive
        url: file:///home/albert/downloads/gyroflow3/flatpak/llvm-project-llvmorg-17.0.6.zip
        sha256: 27b5c7c745ead7e9147c78471b9053d4f6fc3bed94baf45f4e8295439f564bb8
    build-options:
      env:
        CMAKE_INSTALL_PREFIX: /usr
    build-commands:
      - echo "Building libcxx"
      - mkdir build
      - cmake -G Ninja -S runtimes -B build -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi"
      - ninja -C build cxx cxxabi
      #- ninja -C build check-cxx check-cxxabi check-unwind
      - ninja -C build install-cxx install-cxxabi
        
finish-args:
  - --filesystem=home:rw 
  - --socket=wayland
  - --share=ipc
  - --socket=fallback-x11
```

**Comment by Erick555** [comment]
> CMAKE_INSTALL_PREFIX: /usr

This needs to be `CMAKE_INSTALL_PREFIX: /app`

You may also use `buildsystem: cmake-ninja` rather than manual commands

**Comment by Erick555** [comment]
```
modules:
  - name: libcxx
    buildsystem: cmake-ninja
    builddir: true
    subdir: llvm
    sources: 
      - type: archive
        url: file:///home/albert/downloads/gyroflow3/flatpak/llvm-project-llvmorg-17.0.6.zip
        sha256: 27b5c7c745ead7e9147c78471b9053d4f6fc3bed94baf45f4e8295439f564bb8
    config-opts:
      - -DCMAKE_C_COMPILER=clang
      - -DCMAKE_CXX_COMPILER=clang++
      - -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi"
```
